on:
   push:
      branches:
         - main
         - next
         - next-major
         - beta
         - alpha
   workflow_dispatch:

name: semantic-release

jobs:
   release:
      name: Release
      runs-on: ["self-hosted"]
      steps:
         - name: Checkout
           uses: actions/checkout@v4
           with:
              token: ${{ secrets.CI_GITHUB_TOKEN }}
         - name: Setup Node
           uses: actions/setup-node@v3
           with:
              node-version-file: .nvmrc
              cache: npm
              registry-url: https://npm.pkg.github.com/
         - name: Install Dependencies
           run: npm ci
           env:
              NODE_AUTH_TOKEN: ${{ secrets.GHA_PACKAGES }}
         - name: Execute Semantic Release
           env:
              GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
           run: npx semantic-release
         - name: Checkout
           uses: actions/checkout@v4
           with:
              fetch-depth: 0
              token: ${{ secrets.CI_GITHUB_TOKEN }}
           env:
              GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}